version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DATABASE_URL=postgresql://fastapi_quizz:fastapi_quizz@postgres:5432/fastapi_quizz
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - internet
      - localnet

  postgres:
    image: postgres:16-alpine
    container_name: app-postgres
    environment:
      POSTGRES_DB: fastapi_quizz
      POSTGRES_USER: fastapi_quizz
      POSTGRES_PASSWORD: fastapi_quizz
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - localnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge

volumes:
  postgres_data:
